TeamABootcampAplication/TeamABootcampAplication/Controllers/LoginController.cs
namespace TeamABootcampAplication.Controllers
{
    using System;

    #pragma warning disable SA1600 // Elements should be documented

    using Microsoft.AspNetCore.Mvc;
    using RestSharp.Extensions;
    using TeamABootcampAplication.Models;
    using TeamABootcampAplication.Models.Repositorys;
    using TeamABootcampAplication.Models.Services;

    public class LoginController : Controller
    {
        private IUserService userService;
        private IEncryptionService encryptionService;
        private ISessionService sessionService;

        public LoginController()
        {
            this.userService = new UserService(new UserRepository());
            this.sessionService = new SessionService(new SessionRepository());
            this.encryptionService = new EncryptionService();
        }

        public IActionResult Index()
        {
            if (this.Request.Cookies["sessionID"].HasValue())
            {
                return (IActionResult)this.Redirect("/chat");
            }
            else if (this.Request.Cookies["username"].HasValue() && this.Request.Cookies["password"].HasValue())
            {
                this.ViewBag.username = this.Request.Cookies["username"];
                this.ViewBag.password = this.encryptionService.Decrypt(this.Request.Cookies["password"]);
            }

            return this.View();
        }

        public IActionResult Login(string username, string password, string remember)
        {
            int id;
            try
            {
                id = this.userService.Login(username, password);
            }
            catch (ArgumentNullException)
            {
                return this.View("index");
            }

            if (id == 0)
            {
                this.ViewData["Message"] = "*Username or password invalid";

                return this.View("Index");
            }
            else
            {
                if (remember == "on")
                {
                    this.Response.Cookies.Append("username", username);
                    this.Response.Cookies.Append("password", this.encryptionService.Encrypt(password));
                }

                this.Response.Cookies.Append("sessionID", this.sessionService.GenerateSessionID(id));
                this.Response.Cookies.Append("username", username);

                return (IActionResult)this.Redirect("/chat");
            }
        }

        public IActionResult Logout()
        {
            if (!this.Request.Cookies["sessionID"].HasValue())
            {
                return this.Content("Cannot logout");
            }

            if (this.sessionService.RemoveSessionID(this.Request.Cookies["sessionID"].ToString()))
            {
                this.Response.Cookies.Delete("sessionID");
            }

            return (IActionResult)this.Redirect("/");
        }
    }
    #pragma warning restore SA1600 // Elements should be documented
}

TeamABootcampAplication/TeamABootcampAplication/Controllers/RegisterController.cs
namespace TeamABootcampAplication.Controllers
{
    #pragma warning disable SA1600 // Elements should be documented

    using Microsoft.AspNetCore.Mvc;
    using RestSharp.Extensions;
    using TeamABootcampAplication.Models;
    using TeamABootcampAplication.Models.Repositorys;

    public class RegisterController : Controller
    {
        private IUserService userService;

        public RegisterController()
        {
            this.userService = new UserService(new UserRepository());
        }

        public IActionResult Index()
        {
            if (this.Request.Cookies["sessionID"].HasValue())
            {
                return this.Redirect("/chat");
            }
            else
            {
                return this.View("Index");
            }
        }

        public IActionResult Register(string username, string password, string email, string avatar = "")
        {
            if (!this.userService.CreateUser(new Models.User(username, email, avatar, password)))
            {
                this.ViewBag.MessageGood = "*Registration successful";
            }
            else
            {
                this.ViewBag.Message = "Cannot register";
            }

            return this.View("Index");
        }
    }
    #pragma warning restore SA1600 // Elements should be documented
}

TeamABootcampAplication/TeamABootcampAplication/Controllers/ResetPasswordController.cs
namespace TeamABootcampAplication.Controllers
{
    using System;

    #pragma warning disable SA1600 // Elements should be documented

    using Microsoft.AspNetCore.Mvc;
    using RestSharp.Extensions;
    using TeamABootcampAplication.Models;
    using TeamABootcampAplication.Models.Repositorys;
    using TeamABootcampAplication.Models.Services;

    public class ResetPasswordController : Controller
    {
        private IUserService userService;
        private IEmailService emailService;

        public ResetPasswordController()
        {
            this.userService = new UserService(new UserRepository());
            this.emailService = new EmailService();
        }

        public IActionResult Index()
        {
            if (this.Request.Cookies["sessionID"].HasValue())
            {
                return this.Redirect("/chat");
            }
            else
            {
                return this.View("Index");
            }
        }

        public IActionResult ResetPassword(string username, string email)
        {
            try
            {
                string newPassword = this.userService.ChangePassword(username, email);

                if (newPassword.Length != 0)
                {
                    if (this.emailService.SendEmail(email, newPassword))
                    {
                        this.ViewBag.MessageGood = "Check your email!";
                    }
                    else
                    {
                        this.ViewBag.message = "*Can not send email. Try Again!";
                    }
                }
                else
                {
                    this.ViewBag.message = "*Can not generate new password. Try Again!";
                }
            }
            catch (ArgumentNullException)
            {
                this.ViewBag.message = "*Something went wrong. Try Again!";
            }

            return this.View("Index");
        }

        public IActionResult ResetPasswordFromUserPanel(string password, string currentPassword)
        {
            string username = this.Request.Cookies["username"];
            if (this.userService.ChangePasswordFromUserPanel(username, password, currentPassword) != default)
            {
                return this.View("Index");
            }
            else
            {
                return this.ViewBag.message = "Invalid old password";
            }
        }
    }
    #pragma warning restore SA1600 // Elements should be documented
}

TeamABootcampAplication/TeamABootcampAplication/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@using (Html.BeginForm("Login", "Login", FormMethod.Post))
{
<div class="container col-6">
    <div class="card m-6">
        <div class="card-header">
            <h1 class="text-center">Hermes</h1>
            <h2 class="text-center">Login to your account</h2>
        </div>

        <div class="card-body">
            <h1 class="text-danger">@ViewData["Message"]</h1>
            <h1 class="text-success">@ViewBag.MessageGood</h1>

            <div class="form-group">
                <input type="text" class="form-control" placeholder="Username" required name="username" value="@ViewBag.username" maxlength="25">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="Password" required name="password" value="@ViewBag.password" maxlength="30">
            </div>
            <div class="form-group">
                <label>
                    <input type="checkbox" name="remember"> Remember me
                </label>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block">Log in</button>
            </div>
            <div class="form-group text-right">
                <a asp-controller="ResetPassword" asp-action="Index">Forgot your password?</a>
            </div>
            <div class="form-group text-center">
                Don't have an account? <a asp-controller="Register" asp-action="Index">Sign up</a>
            </div>

            <hr class="my-2">
        </div>
    </div>
    @*   --Facebook button
            <div class="form-group">
            <button class="btn-facebook btn btn-primary btn-block">
                Sign in with <b>Facebook</b>
            </button>
        </div>*@
</div>
}