TeamABootcampAplication/TeamABootcampAplication/Controllers/ChatController.cs
namespace SignalR.Hubs
{
    #pragma warning disable SA1600 // Elements should be documented

    using Microsoft.AspNetCore.Mvc;
    using RestSharp.Extensions;

    public class ChatController : Controller
    {
        public IActionResult Index()
        {
            if (!this.Request.Cookies["sessionID"].HasValue())
            {
                return this.Redirect("/");
            }

            return this.View("Index");
        }
    }
    #pragma warning restore SA1600 // Elements should be documented
}

TeamABootcampAplication/TeamABootcampAplication/Controllers/LoginController.cs
namespace TeamABootcampAplication.Controllers
{
    using System;

    #pragma warning disable SA1600 // Elements should be documented

    using Microsoft.AspNetCore.Mvc;
    using RestSharp.Extensions;
    using TeamABootcampAplication.Models;
    using TeamABootcampAplication.Models.Repositorys;
    using TeamABootcampAplication.Models.Services;

    public class LoginController : Controller
    {
        private IUserService userService;
        private IEncryptionService encryptionService;
        private ISessionService sessionService;

        public LoginController()
        {
            this.userService = new UserService(new UserRepository());
            this.sessionService = new SessionService(new SessionRepository());
            this.encryptionService = new EncryptionService();
        }

        public IActionResult Index()
        {
            if (this.Request.Cookies["sessionID"].HasValue())
            {
                return (IActionResult)this.Redirect("/chat");
            }
            else if (this.Request.Cookies["username"].HasValue() && this.Request.Cookies["password"].HasValue())
            {
                this.ViewBag.username = this.Request.Cookies["username"];
                this.ViewBag.password = this.encryptionService.Decrypt(this.Request.Cookies["password"]);
            }

            return this.View();
        }

        public IActionResult Login(string username, string password, string remember)
        {
            int id;
            try
            {
                id = this.userService.Login(username, password);
            }
            catch (ArgumentNullException)
            {
                return this.View("index");
            }

            if (id == 0)
            {
                this.ViewData["Message"] = "*Username or password invalid";

                return this.View("Index");
            }
            else
            {
                if (remember == "on")
                {
                    this.Response.Cookies.Append("username", username);
                    this.Response.Cookies.Append("password", this.encryptionService.Encrypt(password));
                }

                this.Response.Cookies.Append("sessionID", this.sessionService.GenerateSessionID(id));
                this.Response.Cookies.Append("username", username);

                return (IActionResult)this.Redirect("/chat");
            }
        }

        public IActionResult Logout()
        {
            if (!this.Request.Cookies["sessionID"].HasValue())
            {
                return this.Content("Cannot logout");
            }

            if (this.sessionService.RemoveSessionID(this.Request.Cookies["sessionID"].ToString()))
            {
                this.Response.Cookies.Delete("sessionID");
            }

            return (IActionResult)this.Redirect("/");
        }
    }
    #pragma warning restore SA1600 // Elements should be documented
}

TeamABootcampAplication/TeamABootcampAplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
@using RestSharp.Extensions;
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TeamABootcampAplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/emoji/emojionearea.min.css" rel="stylesheet" />  

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="" asp-action="Index">TeamABootcampAplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.Request.Cookies["sessionID"].HasValue()) {
                            @*<li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Chat" asp-action="Index">Chat</a>
                                </li>*@
                        <div class="flex-row-reverse navbar-collapse collapse d-sm-inline-flex">
                            <li class="nav-item">
                                <a class="nav-link text-dark flex-row-reverse" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        </div>
                                
                        }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - TeamABootcampAplication
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/emoji/emojionearea.js"></script> 

        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>